### ISSUE TITLE
[FEATURE] Lower required .NET version

### ISSUE THREAD

**Issue by LiamMorrow** [LiamMorrow/Oatmilk#16]
**Is your feature request related to a problem? Please describe.**
.NET 8 is the latest, ~but is not an LTS~.  Oatmilk doesn't really NEED any of the features it brings, and largely uses it for the latest language features.  .NET 6 might be an okay target,but Xunit supports down to netstadard2.0 (no nullable annotations at that level though...)

**Describe the solution you'd like**

Lower the targeted .net version

**Comment by caviyacht** [comment]
.NET 8 is an LTS release (as was .NET 6). Just to call out that .NET 6 EOL is in November, so using that wouldn't be the greatest move. If it can use netstandard2.0 would probably be preferred.

**Comment by LiamMorrow** [comment]
Oh that's good! I didn't realise this, I thought 9 would be the next. 

Netstandard 2 is probably what I'll aim for anyway, but I'd like to keep nullable annotations
