### ISSUE TITLE
Skip tests when debugger is not running

### ISSUE THREAD

**Issue by smashedtoatoms** [LiamMorrow/Oatmilk#17]
**Is your feature request related to a problem? Please describe.**
Everything works great.  This is a feature request for something no one but me probably cares about.  It can probably be ignored; I just wanted to try my luck.  If this is out of scope, feel free to close immediately.  Thanks for making this library.

**Describe the solution you'd like**
I would like to be able to configure a test or suite of tests so that they run only if a debugger is attached; otherwise, they are skipped. I have a bunch of tests that are not really tests as much as they are verifications made using a debugger, and I would love it if they could be skipped when no debugger is attached.

**Describe alternatives you've considered**
I use XUnit with a custom annotation to automatically skip tests if no debugger is attached.

**Comment by LiamMorrow** [comment]
Wow that's an interesting use case!

~Definitely not against figuring something like that out. I am curious if .Only or just running the specific test with the debugger would cover your use case?~

I just reread your requirements, you ONLY want to run if there's a debugger attached. I'll definitely have a think

**Comment by LiamMorrow** [comment]
I'd be interested in seeing this annotation you use regardless to get some inspiration

**Comment by smashedtoatoms** [comment]
[This article](https://lostechies.com/jimmybogard/2013/06/20/run-tests-explicitly-in-xunit-net/) is where I stole the idea from.  My use case is that I have a bunch of code that is convenient to run from my dev environment using my editor's test runner capabilities, but it operates against a running distributed production system.  It basically lets me inject things and pull things from a running prod system, but I can use the debugger to inspect data and control whether I pass data back into the system or not.  It's a poor man's lisp repl for a running distributed event-driven system.  I don't want those to run when I run all my tests, I only want them to run when I run those individual "tests" with a debugger attached.

**Comment by LiamMorrow** [comment]
That's very fair.

I'm having a play around now to see if I can add some sort of extension point to Oatmilk.

As it stands you could do something like this:

```
public static class ItDebuggerOnlyExtensions
{
 // Body has a couple variants it accepts, but Func<Task> is also valid and usually all you need
  public static void WhenDebuggerAttached(this ItBlock it, Action body)
  {
    (it with { IsSkipped = !System.Diagnostics.Debugger.IsAttached }).When(body);
  }

  public static void IfDebuggerAttached(this DescribeBlock describe, Action body)
  {
    (describe with { IsSkipped = !System.Diagnostics.Debugger.IsAttached }).As(body);
  }
}
```

Usage:

```
    Describe("My test suite").IfDebuggerAttached(() => { });

    It("My test").WhenDebuggerAttached(()=>{
      true.Should().BeTrue();
    });

```


The only problem is you're locked into the fluent syntax there.  

But with that solution it should get you there, here's a demo:

https://github.com/user-attachments/assets/002bc72c-3c8c-4057-a5e9-7307936b079d

**Comment by smashedtoatoms** [comment]
I don't mind at all. The fact that it's possible without mods is really
impressive. Let me play around with that.

**Comment by LiamMorrow** [comment]
I had another thought, if you don't want to deal with all the different overloads (there's no small amount).  You could have the extension method do this:
```
public static class ItDebuggerOnlyExtensions
{
  public static ItBlock WhenDebuggerAttached(this ItBlock it)
  {
    return (it with { IsSkipped = !System.Diagnostics.Debugger.IsAttached });
  }

  public static DescribeBlock IfDebuggerAttached(this DescribeBlock describe)
  {
    return (describe with { IsSkipped = !System.Diagnostics.Debugger.IsAttached });
  }
}
```

Usage:
```
    Describe("My test suite").IfDebuggerAttached().As(()=>{ });

    It("My test").WhenDebuggerAttached().When(()=>{
      true.Should().BeTrue();
    });
```
